name: dg-adw-gtk3-theme
version: '1.0'
architectures:
  - build-on: amd64
    run-on: all
summary: dg-adw-gtk3 theme
description: |
  A Libadwaita + macOS + Yaru GTK3 theme.
build-base: core20
base: bare
compression: lzo

grade: stable
confinement: strict

slots:
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/dg-adw-gtk3-orange
        - $SNAP/share/themes/dg-adw-gtk3-bark
        - $SNAP/share/themes/dg-adw-gtk3-blue
        - $SNAP/share/themes/dg-adw-gtk3-magenta
        - $SNAP/share/themes/dg-adw-gtk3-olive
        - $SNAP/share/themes/dg-adw-gtk3-prussiangreen
        - $SNAP/share/themes/dg-adw-gtk3-purple
        - $SNAP/share/themes/dg-adw-gtk3-red
        - $SNAP/share/themes/dg-adw-gtk3-sage
        - $SNAP/share/themes/dg-adw-gtk3-viridian
        - $SNAP/share/themes/dg-adw-gtk3-orange-dark
        - $SNAP/share/themes/dg-adw-gtk3-bark-dark
        - $SNAP/share/themes/dg-adw-gtk3-blue-dark
        - $SNAP/share/themes/dg-adw-gtk3-magenta-dark
        - $SNAP/share/themes/dg-adw-gtk3-olive-dark
        - $SNAP/share/themes/dg-adw-gtk3-prussiangreen-dark
        - $SNAP/share/themes/dg-adw-gtk3-purple-dark
        - $SNAP/share/themes/dg-adw-gtk3-red-dark
        - $SNAP/share/themes/dg-adw-gtk3-sage-dark
        - $SNAP/share/themes/dg-adw-gtk3-viridian-dark
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/dg-yaru
        - $SNAP/share/icons/dg-yaru-bark
        - $SNAP/share/icons/dg-yaru-blue
        - $SNAP/share/icons/dg-yaru-magenta
        - $SNAP/share/icons/dg-yaru-olive
        - $SNAP/share/icons/dg-yaru-prussiangreen
        - $SNAP/share/icons/dg-yaru-purple
        - $SNAP/share/icons/dg-yaru-red
        - $SNAP/share/icons/dg-yaru-sage
        - $SNAP/share/icons/dg-yaru-viridian
        - $SNAP/share/icons/dg-yaru-dark
        - $SNAP/share/icons/dg-yaru-bark-dark
        - $SNAP/share/icons/dg-yaru-blue-dark
        - $SNAP/share/icons/dg-yaru-magenta-dark
        - $SNAP/share/icons/dg-yaru-olive-dark
        - $SNAP/share/icons/dg-yaru-prussiangreen-dark
        - $SNAP/share/icons/dg-yaru-purple-dark
        - $SNAP/share/icons/dg-yaru-red-dark
        - $SNAP/share/icons/dg-yaru-sage-dark
        - $SNAP/share/icons/dg-yaru-viridian-dark
  sound-themes:
    interface: content
    source:
      read:
        - $SNAP/share/sounds/dg-yaru

parts:
  # dg-adw-gtk3
  dg-adw-gtk3:
    after: [utils]
    source: https://github.com/dgmarie/dg-adw-gtk3.git
    source-depth: 1
    source-commit: e6346c8cd2383219dadcf91991e4d80229a79df0
    plugin: meson
    meson-parameters:
      - --prefix=/
    build-packages:
      - sassc
      - rsync
    override-build: |
      snapcraftctl build
      snapcraftctl set-version "$(git describe --tags 2>/dev/null || echo 1.0)"
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/themes
    stage:
      - share/themes

  # dg-yaru
  dg-yaru:
    after: [utils]
    source: https://github.com/dgmarie/dg-yaru.git
    source-depth: 1
    source-commit: 37a8d6c04ccd292c3b0af7b5e56e9e9234025371
    plugin: meson
    meson-parameters:
      - --prefix=/
      - -Dgnome-shell=false
    override-build: |
      snapcraftctl build
      snapcraftctl set-version "$(git describe --tags 2>/dev/null || echo 1.0)"
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/sounds
      $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
    stage:
      - share/icons
      - share/sounds

  utils:
    plugin: dump
    source: utils
    prime:
      - -*
    build-packages:
      - try: [gtk-update-icon-cache]
      - else: [libgtk-3-bin]
